name: quran_api
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: ^4.6.5
  dio: ^5.4.1
  simple_circular_progress_bar: 1.0.2
  http: 1.2.1
  lottie: 3.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - asset/images/
    - asset/icons/
  uses-material-design: true

